/*
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.ui.labeling;

import com.google.inject.Inject;

import cuisine.recipe.recipe.*;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class RecipeLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public RecipeLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	// Labels and icons can be computed like this:
	
	String text(Technique tech) {
		return tech.getName();
	}

	String image(Technique tech) {
		return "tech.gif";
	}
	
	String text(Recipe rec) {
		return "Recette : " + rec.getName().toString();
	}

	String image(Recipe rec) {
		return "recipe.gif";
	}
	
	String image(Ustensil ust) {
		return "utensil.gif";
	}
	
	String image(Ingredient ing) {
		return "ingredient.gif";
	}
	
	String image(Instruction tech) {
		return "instruction.gif";
	}
}
