/**
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.recipe.impl;

import cuisine.recipe.recipe.Ingredients;
import cuisine.recipe.recipe.Instructions;
import cuisine.recipe.recipe.Recipe;
import cuisine.recipe.recipe.RecipePackage;
import cuisine.recipe.recipe.Ustensils;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Recipe</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link cuisine.recipe.recipe.impl.RecipeImpl#getName <em>Name</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.impl.RecipeImpl#getSuitename <em>Suitename</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.impl.RecipeImpl#getTime <em>Time</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.impl.RecipeImpl#getNb <em>Nb</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.impl.RecipeImpl#getIngredients <em>Ingredients</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.impl.RecipeImpl#getUstensils <em>Ustensils</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.impl.RecipeImpl#getInstructions <em>Instructions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RecipeImpl extends MinimalEObjectImpl.Container implements Recipe
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getSuitename() <em>Suitename</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuitename()
   * @generated
   * @ordered
   */
  protected EList<String> suitename;

  /**
   * The default value of the '{@link #getTime() <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime()
   * @generated
   * @ordered
   */
  protected static final double TIME_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getTime() <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTime()
   * @generated
   * @ordered
   */
  protected double time = TIME_EDEFAULT;

  /**
   * The default value of the '{@link #getNb() <em>Nb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNb()
   * @generated
   * @ordered
   */
  protected static final double NB_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getNb() <em>Nb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNb()
   * @generated
   * @ordered
   */
  protected double nb = NB_EDEFAULT;

  /**
   * The cached value of the '{@link #getIngredients() <em>Ingredients</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIngredients()
   * @generated
   * @ordered
   */
  protected Ingredients ingredients;

  /**
   * The cached value of the '{@link #getUstensils() <em>Ustensils</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUstensils()
   * @generated
   * @ordered
   */
  protected Ustensils ustensils;

  /**
   * The cached value of the '{@link #getInstructions() <em>Instructions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstructions()
   * @generated
   * @ordered
   */
  protected Instructions instructions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RecipeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RecipePackage.Literals.RECIPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RecipePackage.RECIPE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getSuitename()
  {
    if (suitename == null)
    {
      suitename = new EDataTypeEList<String>(String.class, this, RecipePackage.RECIPE__SUITENAME);
    }
    return suitename;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getTime()
  {
    return time;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTime(double newTime)
  {
    double oldTime = time;
    time = newTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RecipePackage.RECIPE__TIME, oldTime, time));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getNb()
  {
    return nb;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNb(double newNb)
  {
    double oldNb = nb;
    nb = newNb;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RecipePackage.RECIPE__NB, oldNb, nb));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ingredients getIngredients()
  {
    return ingredients;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIngredients(Ingredients newIngredients, NotificationChain msgs)
  {
    Ingredients oldIngredients = ingredients;
    ingredients = newIngredients;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RecipePackage.RECIPE__INGREDIENTS, oldIngredients, newIngredients);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIngredients(Ingredients newIngredients)
  {
    if (newIngredients != ingredients)
    {
      NotificationChain msgs = null;
      if (ingredients != null)
        msgs = ((InternalEObject)ingredients).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RecipePackage.RECIPE__INGREDIENTS, null, msgs);
      if (newIngredients != null)
        msgs = ((InternalEObject)newIngredients).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RecipePackage.RECIPE__INGREDIENTS, null, msgs);
      msgs = basicSetIngredients(newIngredients, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RecipePackage.RECIPE__INGREDIENTS, newIngredients, newIngredients));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ustensils getUstensils()
  {
    return ustensils;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUstensils(Ustensils newUstensils, NotificationChain msgs)
  {
    Ustensils oldUstensils = ustensils;
    ustensils = newUstensils;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RecipePackage.RECIPE__USTENSILS, oldUstensils, newUstensils);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUstensils(Ustensils newUstensils)
  {
    if (newUstensils != ustensils)
    {
      NotificationChain msgs = null;
      if (ustensils != null)
        msgs = ((InternalEObject)ustensils).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RecipePackage.RECIPE__USTENSILS, null, msgs);
      if (newUstensils != null)
        msgs = ((InternalEObject)newUstensils).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RecipePackage.RECIPE__USTENSILS, null, msgs);
      msgs = basicSetUstensils(newUstensils, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RecipePackage.RECIPE__USTENSILS, newUstensils, newUstensils));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Instructions getInstructions()
  {
    return instructions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInstructions(Instructions newInstructions, NotificationChain msgs)
  {
    Instructions oldInstructions = instructions;
    instructions = newInstructions;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, RecipePackage.RECIPE__INSTRUCTIONS, oldInstructions, newInstructions);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInstructions(Instructions newInstructions)
  {
    if (newInstructions != instructions)
    {
      NotificationChain msgs = null;
      if (instructions != null)
        msgs = ((InternalEObject)instructions).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - RecipePackage.RECIPE__INSTRUCTIONS, null, msgs);
      if (newInstructions != null)
        msgs = ((InternalEObject)newInstructions).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - RecipePackage.RECIPE__INSTRUCTIONS, null, msgs);
      msgs = basicSetInstructions(newInstructions, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RecipePackage.RECIPE__INSTRUCTIONS, newInstructions, newInstructions));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RecipePackage.RECIPE__INGREDIENTS:
        return basicSetIngredients(null, msgs);
      case RecipePackage.RECIPE__USTENSILS:
        return basicSetUstensils(null, msgs);
      case RecipePackage.RECIPE__INSTRUCTIONS:
        return basicSetInstructions(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RecipePackage.RECIPE__NAME:
        return getName();
      case RecipePackage.RECIPE__SUITENAME:
        return getSuitename();
      case RecipePackage.RECIPE__TIME:
        return getTime();
      case RecipePackage.RECIPE__NB:
        return getNb();
      case RecipePackage.RECIPE__INGREDIENTS:
        return getIngredients();
      case RecipePackage.RECIPE__USTENSILS:
        return getUstensils();
      case RecipePackage.RECIPE__INSTRUCTIONS:
        return getInstructions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RecipePackage.RECIPE__NAME:
        setName((String)newValue);
        return;
      case RecipePackage.RECIPE__SUITENAME:
        getSuitename().clear();
        getSuitename().addAll((Collection<? extends String>)newValue);
        return;
      case RecipePackage.RECIPE__TIME:
        setTime((Double)newValue);
        return;
      case RecipePackage.RECIPE__NB:
        setNb((Double)newValue);
        return;
      case RecipePackage.RECIPE__INGREDIENTS:
        setIngredients((Ingredients)newValue);
        return;
      case RecipePackage.RECIPE__USTENSILS:
        setUstensils((Ustensils)newValue);
        return;
      case RecipePackage.RECIPE__INSTRUCTIONS:
        setInstructions((Instructions)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RecipePackage.RECIPE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case RecipePackage.RECIPE__SUITENAME:
        getSuitename().clear();
        return;
      case RecipePackage.RECIPE__TIME:
        setTime(TIME_EDEFAULT);
        return;
      case RecipePackage.RECIPE__NB:
        setNb(NB_EDEFAULT);
        return;
      case RecipePackage.RECIPE__INGREDIENTS:
        setIngredients((Ingredients)null);
        return;
      case RecipePackage.RECIPE__USTENSILS:
        setUstensils((Ustensils)null);
        return;
      case RecipePackage.RECIPE__INSTRUCTIONS:
        setInstructions((Instructions)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RecipePackage.RECIPE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case RecipePackage.RECIPE__SUITENAME:
        return suitename != null && !suitename.isEmpty();
      case RecipePackage.RECIPE__TIME:
        return time != TIME_EDEFAULT;
      case RecipePackage.RECIPE__NB:
        return nb != NB_EDEFAULT;
      case RecipePackage.RECIPE__INGREDIENTS:
        return ingredients != null;
      case RecipePackage.RECIPE__USTENSILS:
        return ustensils != null;
      case RecipePackage.RECIPE__INSTRUCTIONS:
        return instructions != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", suitename: ");
    result.append(suitename);
    result.append(", time: ");
    result.append(time);
    result.append(", nb: ");
    result.append(nb);
    result.append(')');
    return result.toString();
  }

} //RecipeImpl
