/**
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.recipe;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>choices</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cuisine.recipe.recipe.choices#getChoix <em>Choix</em>}</li>
 * </ul>
 *
 * @see cuisine.recipe.recipe.RecipePackage#getchoices()
 * @model
 * @generated
 */
public interface choices extends EObject
{
  /**
   * Returns the value of the '<em><b>Choix</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choix</em>' attribute list.
   * @see cuisine.recipe.recipe.RecipePackage#getchoices_Choix()
   * @model unique="false"
   * @generated
   */
  EList<String> getChoix();

} // choices
