/**
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.recipe;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ingredients</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cuisine.recipe.recipe.Ingredients#getIngr <em>Ingr</em>}</li>
 * </ul>
 *
 * @see cuisine.recipe.recipe.RecipePackage#getIngredients()
 * @model
 * @generated
 */
public interface Ingredients extends EObject
{
  /**
   * Returns the value of the '<em><b>Ingr</b></em>' containment reference list.
   * The list contents are of type {@link cuisine.recipe.recipe.Ingredient}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ingr</em>' containment reference list.
   * @see cuisine.recipe.recipe.RecipePackage#getIngredients_Ingr()
   * @model containment="true"
   * @generated
   */
  EList<Ingredient> getIngr();

} // Ingredients
