/**
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.recipe;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ingredient</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cuisine.recipe.recipe.Ingredient#getName <em>Name</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.Ingredient#getSuitenameIngredient <em>Suitename Ingredient</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.Ingredient#getQte <em>Qte</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.Ingredient#getQuantificateur <em>Quantificateur</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.Ingredient#getGroup <em>Group</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.Ingredient#getTag <em>Tag</em>}</li>
 * </ul>
 *
 * @see cuisine.recipe.recipe.RecipePackage#getIngredient()
 * @model
 * @generated
 */
public interface Ingredient extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see cuisine.recipe.recipe.RecipePackage#getIngredient_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link cuisine.recipe.recipe.Ingredient#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Suitename Ingredient</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Suitename Ingredient</em>' attribute list.
   * @see cuisine.recipe.recipe.RecipePackage#getIngredient_SuitenameIngredient()
   * @model unique="false"
   * @generated
   */
  EList<String> getSuitenameIngredient();

  /**
   * Returns the value of the '<em><b>Qte</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qte</em>' attribute.
   * @see #setQte(double)
   * @see cuisine.recipe.recipe.RecipePackage#getIngredient_Qte()
   * @model
   * @generated
   */
  double getQte();

  /**
   * Sets the value of the '{@link cuisine.recipe.recipe.Ingredient#getQte <em>Qte</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qte</em>' attribute.
   * @see #getQte()
   * @generated
   */
  void setQte(double value);

  /**
   * Returns the value of the '<em><b>Quantificateur</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantificateur</em>' containment reference.
   * @see #setQuantificateur(Quantificateurs)
   * @see cuisine.recipe.recipe.RecipePackage#getIngredient_Quantificateur()
   * @model containment="true"
   * @generated
   */
  Quantificateurs getQuantificateur();

  /**
   * Sets the value of the '{@link cuisine.recipe.recipe.Ingredient#getQuantificateur <em>Quantificateur</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantificateur</em>' containment reference.
   * @see #getQuantificateur()
   * @generated
   */
  void setQuantificateur(Quantificateurs value);

  /**
   * Returns the value of the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group</em>' attribute.
   * @see #setGroup(String)
   * @see cuisine.recipe.recipe.RecipePackage#getIngredient_Group()
   * @model
   * @generated
   */
  String getGroup();

  /**
   * Sets the value of the '{@link cuisine.recipe.recipe.Ingredient#getGroup <em>Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group</em>' attribute.
   * @see #getGroup()
   * @generated
   */
  void setGroup(String value);

  /**
   * Returns the value of the '<em><b>Tag</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tag</em>' attribute.
   * @see #setTag(String)
   * @see cuisine.recipe.recipe.RecipePackage#getIngredient_Tag()
   * @model
   * @generated
   */
  String getTag();

  /**
   * Sets the value of the '{@link cuisine.recipe.recipe.Ingredient#getTag <em>Tag</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tag</em>' attribute.
   * @see #getTag()
   * @generated
   */
  void setTag(String value);

} // Ingredient
