/**
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.recipe;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instructions</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see cuisine.recipe.recipe.RecipePackage#getInstructions()
 * @model
 * @generated
 */
public interface Instructions extends EObject
{
} // Instructions
