/**
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.recipe;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cuisine.recipe.recipe.Instruction#getName <em>Name</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.Instruction#getObj <em>Obj</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.Instruction#getPreparation <em>Preparation</em>}</li>
 * </ul>
 *
 * @see cuisine.recipe.recipe.RecipePackage#getInstruction()
 * @model
 * @generated
 */
public interface Instruction extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see cuisine.recipe.recipe.RecipePackage#getInstruction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link cuisine.recipe.recipe.Instruction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Obj</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj</em>' attribute list.
   * @see cuisine.recipe.recipe.RecipePackage#getInstruction_Obj()
   * @model unique="false"
   * @generated
   */
  EList<String> getObj();

  /**
   * Returns the value of the '<em><b>Preparation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Preparation</em>' containment reference.
   * @see #setPreparation(Ingredient)
   * @see cuisine.recipe.recipe.RecipePackage#getInstruction_Preparation()
   * @model containment="true"
   * @generated
   */
  Ingredient getPreparation();

  /**
   * Sets the value of the '{@link cuisine.recipe.recipe.Instruction#getPreparation <em>Preparation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Preparation</em>' containment reference.
   * @see #getPreparation()
   * @generated
   */
  void setPreparation(Ingredient value);

} // Instruction
