/**
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.recipe;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cuisine.recipe.recipe.Model#getDefTechniques <em>Def Techniques</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.Model#getRecipes <em>Recipes</em>}</li>
 * </ul>
 *
 * @see cuisine.recipe.recipe.RecipePackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Def Techniques</b></em>' containment reference list.
   * The list contents are of type {@link cuisine.recipe.recipe.Technique}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def Techniques</em>' containment reference list.
   * @see cuisine.recipe.recipe.RecipePackage#getModel_DefTechniques()
   * @model containment="true"
   * @generated
   */
  EList<Technique> getDefTechniques();

  /**
   * Returns the value of the '<em><b>Recipes</b></em>' containment reference list.
   * The list contents are of type {@link cuisine.recipe.recipe.Recipe}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recipes</em>' containment reference list.
   * @see cuisine.recipe.recipe.RecipePackage#getModel_Recipes()
   * @model containment="true"
   * @generated
   */
  EList<Recipe> getRecipes();

} // Model
