/**
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.recipe;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Technique</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cuisine.recipe.recipe.Technique#getName <em>Name</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.Technique#getObjectsFac <em>Objects Fac</em>}</li>
 *   <li>{@link cuisine.recipe.recipe.Technique#getObjects <em>Objects</em>}</li>
 * </ul>
 *
 * @see cuisine.recipe.recipe.RecipePackage#getTechnique()
 * @model
 * @generated
 */
public interface Technique extends choices
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see cuisine.recipe.recipe.RecipePackage#getTechnique_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link cuisine.recipe.recipe.Technique#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Objects Fac</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects Fac</em>' attribute list.
   * @see cuisine.recipe.recipe.RecipePackage#getTechnique_ObjectsFac()
   * @model unique="false"
   * @generated
   */
  EList<String> getObjectsFac();

  /**
   * Returns the value of the '<em><b>Objects</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects</em>' attribute list.
   * @see cuisine.recipe.recipe.RecipePackage#getTechnique_Objects()
   * @model unique="false"
   * @generated
   */
  EList<String> getObjects();

} // Technique
