/**
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.recipe;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ustensils</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cuisine.recipe.recipe.Ustensils#getUstr <em>Ustr</em>}</li>
 * </ul>
 *
 * @see cuisine.recipe.recipe.RecipePackage#getUstensils()
 * @model
 * @generated
 */
public interface Ustensils extends EObject
{
  /**
   * Returns the value of the '<em><b>Ustr</b></em>' containment reference list.
   * The list contents are of type {@link cuisine.recipe.recipe.Ustensil}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ustr</em>' containment reference list.
   * @see cuisine.recipe.recipe.RecipePackage#getUstensils_Ustr()
   * @model containment="true"
   * @generated
   */
  EList<Ustensil> getUstr();

} // Ustensils
