/*
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.tests

import com.google.inject.Inject
import cuisine.recipe.recipe.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import java.util.stream.Stream
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.MethodSource

@ExtendWith(InjectionExtension)
@InjectWith(RecipeInjectorProvider)
class RecipeParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Inject extension ValidationTestHelper
	
	Model recipes;
	
	@Test
	def void testRecipe() {
		recipes = parseHelper.parse('''define grill [utensil] ingredient''')
		Assertions.assertNotNull(recipes);
		recipes.assertNoIssues();
	}
	
	@Test
	def void testRecipeFail() {
		recipes = parseHelper.parse('''fromage''')
		Assertions.assertNull(recipes);
	}
	
	def static Stream<String> goodLanguageSequences() {
		return Stream.of(
			'''define grill [utensil] ingredient''',
			'''define grease [utensil]''',
			'''define cut [tool] ingredient {{small, medium, large}, {cubes, slices, bits}}''',
			'''define reserve ingredient''',
			'''define mix [utensil] ingredient [preparation]''',
			'''define pour ingredient [utensil] [preparation]''',
			'''define grill [utensil] ingredient
				define grease [utensil]''',
			'''define grill [utensil] ingredient
			define grease [utensil]
			define cut [utensil] ingredient {{small, medium, large}, {cubes, slices, bits}}
			define reserve ingredient [quantity]
			define heat utensil [temperature]
			define mix [utensil] ingredient [utensil]
			define pour ingredient [utensil] [preparation]
			define distribute ingredient preparation
			define cook ingredient [utensil]
			define put_in ingredient [utensil]
			
			recipe {
				name : Gaufres Trotro (lardons Cheddar et petits oignons)
			    
			    time : 15min
			    
			    nb_pers : 9.5
			        
			    ingredients : {
			    	Lardons Fumés : 100g @lardons,
			        Farine t55 : 140g #sec @farine,
			        Bicarbonate : 0.5cc #sec,
			        Levure chimique : 0.8cc #sec @levure,
			        Sel marin : 1càc #sec @sel,
			        Sucre : 1cs #sec,
			        prika fumé piquant : 1cc #sec @paprika,
			        Oeuf : 1.5 #liquide,
			        Buttermilk du cul : 240g #liquide @lait,
			        Beurre fondu : 15g #liquide @beurre,
			        Graisse des lardons cuits : 1cc #liquide @graisseLC,
			        Cheddar rapé : 100g @cheddar,
			        Petits oignons émincées : 4 @oignons,
			        Oeuf frit : 1 #aled,
			        Sirop d'érable : any #aled
				}
			        
			    utensils : {
			        Poele,
			        Gauffrier,
			        fouet,
			        Grand bol,
			        Petit bol,
			        Louche,
			    	Four
			    }
			        
			    instructions:{
			    	grill Poele, Lardons Fumés "Biens dorés et croustillants";
			        cut Lardons Fumés, small bits -> lardons;
			        reserve Graisse des lardons cuits, 1cs "A ajouter aux ingrédients liquides";
			        heat Gauffrier -> Gaufrier chaud;
			        mix fouet, #sec, Petit bol;
			        mix #liquide, Grand bol ;
			        pour #sec, #liquide -> pate;
			        mix fouet, pate "Plus de trace de farine";
			        distribute lardons, @cheddar, Petits oignons émincées, pate;
			        grease Gaufrier chaud -> Gaufrier chaud et graissé;
			        pour pate, Louche, Gaufrier chaud et graissé -> Gaufre;
			        cook Gaufre "Dorées et fondantes"
			    }
			}
			''',
			'''
			
			define grill [utensil] ingredient [time] [temperature]
			define grease utensil [temperature]
			define reserve [quantity] ingredient [utensil]
			define mix [utensil] ingredient [utensil]
			define tamiser ingredient
			define verser ingredient [utensil] [preparation]
			define trou_centre preparation
			define faire_croix preparation
			define submerger preparation utensil
			define laver_secher ingredient
			define rayer ingredient
			define ajouter ingredient preparation
			define amasser preparation [utensil]
			define preparer utensil
			define sortir preparation utensil
			define laiser_reposer preparation time
			define couvrir preparation utensil
			define donner_forme_boule preparation
			define mettre_les_doigts_au_centre_agrandir_trou preparation
			define poser preparation utensil
			define battre_en_omellette ingredient
			define peindre preparation  preparation
			define humidifier ingredient [utensil]
			define laisser_refroidir preparation
			
			recipe {
				name : Roscon de Reyes Receta navideña
			    
			    time : 360min
			
			    nb_pers : 10
			    
			    ingredients: {
			    	farine semicomplète : 150g #preferment @pre_farine,
			    	lait entier tiède: 10 dL #preferment @pre_lait,
			    	sucre : 1 cc @pre_sucre,
			    	levure de boulangerie: 12.5 g #pate @pre_levure,
			    	levure sèche de boulangerie: 4.5 g #pate @pre_levure,
			    	farine semicomplète: 550g #pate @pate_farine,
			    	lait entier tiède: 10 dL #pate @pate_lait,
			    	levure de boulangerie: 12.5 g #pate @pate_levure,
			    	levure sèche de boulangerie: 8 g #pate @pate_levure,
			    	oeufs: 3 #pate @pate_oeufs,
			    	orange:1 #pate @orange,
			    	citron:1 #pate @citron,
			    	fève:1,
			    	beurre en pommade:100g #pate @pate_beurre,
			    	essence d'orange : 30cl #pate @essence_orange,
			    	sucre: 200 g #pate @pate_sucre,
			    	rhom: 2 cs #pate @rhom,
			    	essence de vanille : 1 cc #pate @essence_vanille,
			    	sel: 0.5 cc #pate @sel,
			    	oeufs: 2 #deco @oeufs_deco,
			    	lait : 1 cc #deco @lait_deco,
			    	eau: 2 cc #deco @eau_deco,
			    	fruits confits: any #deco @fruit_confit_deco
			    }
			    utensils: {
			    	grand bol @gbol,
			    	petit bol @pbol,
			    	bol avec eau tiède @eau,
			    	cuillère ou fourchette @cuil,
			    	cuillere en bois @cuillere_en_bois,
			    	mains @mains,
			    	doigts,
			    	plaque,
			    	four,
			    	fouet,
			    	assiette,
			    	zoneAmasage,
			    	torchon
			    }
					    
			   instructions: {
			   		verser @cuil, @pre_levure, @pre_lait, @pbol -> lait_avec_levure;
			      	verser @pre_farine, @pbol -> melange;
			      	trou_centre melange;
			      	verser lait_avec_levure, melange -> melange;
			      	mix @cuil, melange;
			      	mix @mains, melange -> boule;
			      	faire_croix boule;
			      	submerger boule, @eau "qui tombe au fond puis au bout de 10 minutes monte à la surface et aura doublée de taille";
			      	reserve boule, @pbol;
			      	tamiser @pate_farine -> farine_tamisée;
			      	verser farine_tamisée, @gbol -> farine_dans_bol;
			      	reserve 4cc, farine_tamisée "pour engorger la pate" -> reste_farine;
			      	laver_secher orange;
			      	rayer orange -> zeste_orange;
			      	laver_secher citron;
			      	rayer citron -> zeste_citron;
			      	reserve zeste_orange, zeste_citron, assiette -> zestes;
			      	verser sucre, oeufs, @gbol -> oeufs_sucre;
			      	mix oeufs_sucre;
			      	verser zestes, @essence_vanille, @rhom, @sel, oeufs_sucre -> mix_oeuf_sucre_zestes;
			      	mix mix_oeuf_sucre_zestes;
			      	verser @pate_levure, @pate_lait, @pbol -> lait_avec_levure;
			      	trou_centre farine_dans_bol;
			      	verser lait_avec_levure, mix_oeuf_sucre_zestes, farine_dans_bol -> melange;
			      	mix cuillere en bois, melange;
			      	ajouter @pate_beurre, @essence_orange, boule, melange -> début_pate;
			      	mix @cuillere_en_bois, début_pate "pendant 5 minutes";
			   		preparer zoneAmasage;
			   		verser reste_farine, zoneAmasage;
			   		sortir début_pate, @gbol;
			   		amasser début_pate, mains "au fur et à mesure la pate se manipulera plus rapidement, restant élastique et homogène (pas plus de 45 minutes)";
			   		laiser_reposer début_pate, 10min "après 15min d'amassage";
			   		amasser début_pate, mains "au fur et à mesure la pate se manipulera plus rapidement, restant élastique et homogène (pas plus de 45 minutes)"->pate;
			   		verser reste_farine, @gbol;
			   		verser pate, @gbol;
			   		couvrir pate, torchon "pendant 3h minimum la pate aura doublé ou triplé de volume";
			   		donner_forme_boule pate;
			   		mettre_les_doigts_au_centre_agrandir_trou pate "pate de forme ovale"-> roscon_cru;
			   		ajouter fève, roscon_cru;
			   		poser roscon_cru, plaque;
			   		couvrir roscon_cru, torchon "pendant 2h minimum la pate aura doublé ou triplé de volume";
			   		battre_en_omellette oeufs;
			   		verser lait, oeufs "pour éviter que l'oeuf ne brule et qu'il soit super joli" -> mélange_lait_oeuf;
			   		peindre roscon_cru, mélange_lait_oeuf;
			   		humidifier sucre, @pbol->sucre_granulé;
			   		mix doigts, sucre_granulé;
			   		verser sucre_granulé, roscon_cru;
			   		poser fruits confits, roscon_cru;
			   		grease four, 200°C;
			   		grill four, roscon_cru, 20min, 180°C-> roscon_cuit;
			   		sortir roscon_cuit , four 
			    }
			}
			'''
		);
	}
	
	@ParameterizedTest
	@MethodSource("goodLanguageSequences")
	def void testSequences(String seq) {
		recipes = parseHelper.parse(seq)
		Assertions.assertNotNull(recipes)
		recipes.assertNoIssues
	}	
}
