/*
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.ui.outline;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import cuisine.recipe.recipe.*;
import cuisine.recipe.validation.RecipeValidator;

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
public class RecipeOutlineTreeProvider extends DefaultOutlineTreeProvider {
	List<CustomString> preparations = new ArrayList<>();
	public Object _text(Technique technique) {
		if(!(technique==null)) {
			return technique.getName();
		}
		return technique;
	}
	
	public Object _text(ParamTechnique param) {
		if(!(param.getObject()==null)) {
			return param.getObject();
		} else if(!(param.getObjectFac()==null)) {
			return "Facultatif "+param.getObjectFac();
		} else {
			return "Choices";
		}
	}
	public Object _text(Time time) {
		if(time.getTimeUnit().equals("s")) {
			return time.getTime()+" seconds";
		} else if(time.getTimeUnit().equals("min")) {
			return time.getTime()+" minutes";
		} else if(time.getTimeUnit().equals("h")) {
			return time.getTime()+" hours";
		} else {
			return time.getTime()+" days";
		}
	}
	
	public Object _text(Choices choices) {
		return "[]";
	}
	
	public Object _text(Choice choices) {
		return "[]";
	}
	
	public Object _text(Recipe recipe) {
		return _text(recipe.getName());
	}

   public Object _text(IngredientList ingrs) {
	   return "Ingredients";  
   }
	
	public Object _text(Ingredient ing) {
		if(ing.getName()!=null) {
			return _text(ing.getName());
		}
		return ing;
	}
	
	public Object _text(Quantity qte) {
		if(qte.getQt()==0.0) {
			return "quelques";
		} else {
			return qte.getQt()+"";
		}
	}
	
	public Object _text(Quantifier qt) {
		if(qt.getMesure().equals("càc")||qt.getMesure().equals("cc")) {
			return "cuillère à café";
		} else if(qt.getMesure().equals("càs")||qt.getMesure().equals("cs")) {
			return "cuillère à soupe";
		} else {
			return qt.getMesure();
		}
	}

   public Object _text(UtensilList usts) {
	return "Ustensils";
	   
   }

   public Object _text(Utensil ust) {
	return _text(ust.getName());
   }
   
   public Object _text(InstructionList insts) {
	return "Instructions";
   }

   public Object _text(Instruction inst) {
	if(inst.getPreparation()!=null) {
		preparations.add(inst.getPreparation());
	}
	return inst.getTechnique();
   }
   
   public void _createChildren(IOutlineNode parent, Instruction instruction) {
	   // Getting the root of the model
       EObject rootElement = EcoreUtil2.getRootContainer(instruction);
       // Getting all the instances of Technique in the model
       List<Technique> techniques = EcoreUtil2.getAllContentsOfType(rootElement, Technique.class);
       for(Technique t : techniques) {
    	   if(t.getName().equals(instruction.getTechnique())) {
    		   createNode(parent, t);
    	   }
       }
       for(InstructionParameter param : instruction.getParameters()) {
    	   if(param!=null) {
    		   if((param.getQt()==null || param.getTemp()==null || param.getTime()==null) && (param.getAtag()!=null || param.getHtag()!=null || param.getParameter()!=null)) {
    			   createNode(parent, param);
    		   } else if(param.getQte()!=0) {
        		   if(param.getQt()!=null || param.getTemp()!=null || param.getTime()!=null) {
        			   createNode(parent, param);
        		   }
    		   }
    	   }
       }
       if(instruction.getPreparation()!=null) {
    	   createNode(parent, instruction.getPreparation());
       }
	}
   
	public Object _text(InstructionParameter param) {
		if(!(param.getAtag()==null)) {
			return "@"+param.getAtag(); 
		} else if(!(param.getHtag()==null)) {
			return "#"+param.getHtag(); 
		} else if(!(param.getQt()==null)) {
			return param.getQte()+" "+_text(param.getQt());
		} else if(!(param.getTime()==null)) {
			return param.getQte()+" "+param.getTime();
		}else if(!(param.getTemp()==null)) {
			return param.getQte()+" "+param.getTemp();
		}else if(param.getParameter()!=null){
			return _text(param.getParameter());
		}
		return param;
	}
	
    protected boolean _isLeaf(InstructionParameter param) {
        return false;
    }
    
    public void _createChildren(IOutlineNode parent, InstructionParameter param) {
    	EObject r = EcoreUtil2.getContainerOfType(param, Recipe.class);
		if(!(param.getAtag()==null)) {
			createNode(parent, RecipeValidator.getIngredientOrUstensilFromATag(param.getAtag(),(Recipe) r));
		} else if(!(param.getHtag()==null)) {
			for(Ingredient i : RecipeValidator.getIngredientsFromHTag(param.getHtag(),(Recipe) r)) {
				createNode(parent, i);
			}
		} else if(!(param.getParameter()==null)) {
			EObject e = (EObject) RecipeValidator.getIngredientOrUstensilOrPreparationFromName(param.getParameter(),(Recipe) r);
			if(e!=null) {
				createNode(parent, e);
			}
		}
	}

	public Object _text(CustomString str) {
		return RecipeValidator.customStringToString(str);
	}

	public Object _text(Model model) {
		return "Livre de recette";
	}
}