/*
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.parser.antlr;

import com.google.inject.Inject;
import cuisine.recipe.parser.antlr.internal.InternalRecipeParser;
import cuisine.recipe.services.RecipeGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RecipeParser extends AbstractAntlrParser {

	@Inject
	private RecipeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRecipeParser createParser(XtextTokenStream stream) {
		return new InternalRecipeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public RecipeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RecipeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
