/*
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RecipeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("cuisine/recipe/parser/antlr/internal/InternalRecipe.tokens");
	}
}
