/*
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RecipeUiModule extends AbstractRecipeUiModule {

	public RecipeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
