/*
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.ui.tests;

import com.google.inject.Injector;
import cuisine.recipe.ui.internal.RecipeActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RecipeUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RecipeActivator.getInstance().getInjector("cuisine.recipe.Recipe");
	}

}
