/*
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRecipeScopeProvider extends DelegatingScopeProvider {
}
