/*
 * generated by Xtext 2.23.0
 */
package cuisine.recipe.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RecipeGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDefTechniquesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDefTechniquesTechniqueParserRuleCall_0_0 = (RuleCall)cDefTechniquesAssignment_0.eContents().get(0);
		private final Assignment cRecipesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRecipesRecipeParserRuleCall_1_0 = (RuleCall)cRecipesAssignment_1.eContents().get(0);
		
		//Model:
		//	defTechniques+=Technique* recipes+=Recipe*;
		@Override public ParserRule getRule() { return rule; }
		
		//defTechniques+=Technique* recipes+=Recipe*
		public Group getGroup() { return cGroup; }
		
		//defTechniques+=Technique*
		public Assignment getDefTechniquesAssignment_0() { return cDefTechniquesAssignment_0; }
		
		//Technique
		public RuleCall getDefTechniquesTechniqueParserRuleCall_0_0() { return cDefTechniquesTechniqueParserRuleCall_0_0; }
		
		//recipes+=Recipe*
		public Assignment getRecipesAssignment_1() { return cRecipesAssignment_1; }
		
		//Recipe
		public RuleCall getRecipesRecipeParserRuleCall_1_0() { return cRecipesRecipeParserRuleCall_1_0; }
	}
	public class TechniqueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.Technique");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDefineKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cObjectsFacAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cObjectsFacIngrUslTechParserRuleCall_2_0_1_0 = (RuleCall)cObjectsFacAssignment_2_0_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_0_2 = (Keyword)cGroup_2_0.eContents().get(2);
		private final Assignment cObjectsAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cObjectsIngrUslTechParserRuleCall_2_1_0 = (RuleCall)cObjectsAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cAlternatives_2.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final RuleCall cChoicesParserRuleCall_2_2_1 = (RuleCall)cGroup_2_2.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_2_2_2 = (Keyword)cGroup_2_2.eContents().get(2);
		
		//Technique:
		//	"define" name=ID ("[" objectsFac+=IngrUslTech "]" | objects+=IngrUslTech | "{" choices "}")+;
		@Override public ParserRule getRule() { return rule; }
		
		//"define" name=ID ("[" objectsFac+=IngrUslTech "]" | objects+=IngrUslTech | "{" choices "}")+
		public Group getGroup() { return cGroup; }
		
		//"define"
		public Keyword getDefineKeyword_0() { return cDefineKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//("[" objectsFac+=IngrUslTech "]" | objects+=IngrUslTech | "{" choices "}")+
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//"[" objectsFac+=IngrUslTech "]"
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//"["
		public Keyword getLeftSquareBracketKeyword_2_0_0() { return cLeftSquareBracketKeyword_2_0_0; }
		
		//objectsFac+=IngrUslTech
		public Assignment getObjectsFacAssignment_2_0_1() { return cObjectsFacAssignment_2_0_1; }
		
		//IngrUslTech
		public RuleCall getObjectsFacIngrUslTechParserRuleCall_2_0_1_0() { return cObjectsFacIngrUslTechParserRuleCall_2_0_1_0; }
		
		//"]"
		public Keyword getRightSquareBracketKeyword_2_0_2() { return cRightSquareBracketKeyword_2_0_2; }
		
		//objects+=IngrUslTech
		public Assignment getObjectsAssignment_2_1() { return cObjectsAssignment_2_1; }
		
		//IngrUslTech
		public RuleCall getObjectsIngrUslTechParserRuleCall_2_1_0() { return cObjectsIngrUslTechParserRuleCall_2_1_0; }
		
		//"{" choices "}"
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_2_0() { return cLeftCurlyBracketKeyword_2_2_0; }
		
		//choices
		public RuleCall getChoicesParserRuleCall_2_2_1() { return cChoicesParserRuleCall_2_2_1; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_2_2_2() { return cRightCurlyBracketKeyword_2_2_2; }
	}
	public class ChoicesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.choices");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cChoixAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cChoixIDTerminalRuleCall_0_0_0 = (RuleCall)cChoixAssignment_0_0.eContents().get(0);
		private final Group cGroup_0_1 = (Group)cGroup_0.eContents().get(1);
		private final Keyword cCommaKeyword_0_1_0 = (Keyword)cGroup_0_1.eContents().get(0);
		private final Assignment cChoixAssignment_0_1_1 = (Assignment)cGroup_0_1.eContents().get(1);
		private final RuleCall cChoixIDTerminalRuleCall_0_1_1_0 = (RuleCall)cChoixAssignment_0_1_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cChoicesParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_1_3 = (Group)cGroup_1.eContents().get(3);
		private final Keyword cCommaKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1_3_1 = (Keyword)cGroup_1_3.eContents().get(1);
		private final RuleCall cChoicesParserRuleCall_1_3_2 = (RuleCall)cGroup_1_3.eContents().get(2);
		private final Keyword cRightCurlyBracketKeyword_1_3_3 = (Keyword)cGroup_1_3.eContents().get(3);
		
		//fragment choices:
		//	choix+=ID ("," choix+=ID)* | "{" choices "}" ("," "{" choices "}")*;
		@Override public ParserRule getRule() { return rule; }
		
		//choix+=ID ("," choix+=ID)* | "{" choices "}" ("," "{" choices "}")*
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//choix+=ID ("," choix+=ID)*
		public Group getGroup_0() { return cGroup_0; }
		
		//choix+=ID
		public Assignment getChoixAssignment_0_0() { return cChoixAssignment_0_0; }
		
		//ID
		public RuleCall getChoixIDTerminalRuleCall_0_0_0() { return cChoixIDTerminalRuleCall_0_0_0; }
		
		//("," choix+=ID)*
		public Group getGroup_0_1() { return cGroup_0_1; }
		
		//","
		public Keyword getCommaKeyword_0_1_0() { return cCommaKeyword_0_1_0; }
		
		//choix+=ID
		public Assignment getChoixAssignment_0_1_1() { return cChoixAssignment_0_1_1; }
		
		//ID
		public RuleCall getChoixIDTerminalRuleCall_0_1_1_0() { return cChoixIDTerminalRuleCall_0_1_1_0; }
		
		//"{" choices "}" ("," "{" choices "}")*
		public Group getGroup_1() { return cGroup_1; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_1_0() { return cLeftCurlyBracketKeyword_1_0; }
		
		//choices
		public RuleCall getChoicesParserRuleCall_1_1() { return cChoicesParserRuleCall_1_1; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_1_2() { return cRightCurlyBracketKeyword_1_2; }
		
		//("," "{" choices "}")*
		public Group getGroup_1_3() { return cGroup_1_3; }
		
		//","
		public Keyword getCommaKeyword_1_3_0() { return cCommaKeyword_1_3_0; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_1_3_1() { return cLeftCurlyBracketKeyword_1_3_1; }
		
		//choices
		public RuleCall getChoicesParserRuleCall_1_3_2() { return cChoicesParserRuleCall_1_3_2; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_1_3_3() { return cRightCurlyBracketKeyword_1_3_3; }
	}
	public class IngrUslTechElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.IngrUslTech");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cIngredientKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cUstensilKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cPreparationKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cTemperatureKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cToolKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		
		//IngrUslTech:
		//	"ingredient" | "ustensil" | "preparation" | "temperature" | "tool";
		@Override public ParserRule getRule() { return rule; }
		
		//"ingredient" | "ustensil" | "preparation" | "temperature" | "tool"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"ingredient"
		public Keyword getIngredientKeyword_0() { return cIngredientKeyword_0; }
		
		//"ustensil"
		public Keyword getUstensilKeyword_1() { return cUstensilKeyword_1; }
		
		//"preparation"
		public Keyword getPreparationKeyword_2() { return cPreparationKeyword_2; }
		
		//"temperature"
		public Keyword getTemperatureKeyword_3() { return cTemperatureKeyword_3; }
		
		//"tool"
		public Keyword getToolKeyword_4() { return cToolKeyword_4; }
	}
	public class RecipeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.Recipe");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRecipeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameIDTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Assignment cSuitenameAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSuitenameIDTerminalRuleCall_5_0 = (RuleCall)cSuitenameAssignment_5.eContents().get(0);
		private final Keyword cTimeKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cColonKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTimeAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTimeDOUBLETerminalRuleCall_8_0 = (RuleCall)cTimeAssignment_8.eContents().get(0);
		private final Keyword cNb_persKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cColonKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cNbAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cNbDOUBLETerminalRuleCall_11_0 = (RuleCall)cNbAssignment_11.eContents().get(0);
		private final Assignment cIngredientsAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cIngredientsIngredientsParserRuleCall_12_0 = (RuleCall)cIngredientsAssignment_12.eContents().get(0);
		private final Assignment cUstensilsAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cUstensilsUstensilsParserRuleCall_13_0 = (RuleCall)cUstensilsAssignment_13.eContents().get(0);
		private final Assignment cInstructionsAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cInstructionsInstructionsParserRuleCall_14_0 = (RuleCall)cInstructionsAssignment_14.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Recipe:
		//	"recipe" "{" "name" ":" name=ID suitename+=ID* "time" ":" time=DOUBLE "nb_pers" ":" nb=DOUBLE ingredients=Ingredients
		//	ustensils=Ustensils instructions=Instructions "}";
		@Override public ParserRule getRule() { return rule; }
		
		//"recipe" "{" "name" ":" name=ID suitename+=ID* "time" ":" time=DOUBLE "nb_pers" ":" nb=DOUBLE ingredients=Ingredients
		//ustensils=Ustensils instructions=Instructions "}"
		public Group getGroup() { return cGroup; }
		
		//"recipe"
		public Keyword getRecipeKeyword_0() { return cRecipeKeyword_0; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//"name"
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }
		
		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//name=ID
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_4_0() { return cNameIDTerminalRuleCall_4_0; }
		
		//suitename+=ID*
		public Assignment getSuitenameAssignment_5() { return cSuitenameAssignment_5; }
		
		//ID
		public RuleCall getSuitenameIDTerminalRuleCall_5_0() { return cSuitenameIDTerminalRuleCall_5_0; }
		
		//"time"
		public Keyword getTimeKeyword_6() { return cTimeKeyword_6; }
		
		//":"
		public Keyword getColonKeyword_7() { return cColonKeyword_7; }
		
		//time=DOUBLE
		public Assignment getTimeAssignment_8() { return cTimeAssignment_8; }
		
		//DOUBLE
		public RuleCall getTimeDOUBLETerminalRuleCall_8_0() { return cTimeDOUBLETerminalRuleCall_8_0; }
		
		//"nb_pers"
		public Keyword getNb_persKeyword_9() { return cNb_persKeyword_9; }
		
		//":"
		public Keyword getColonKeyword_10() { return cColonKeyword_10; }
		
		//nb=DOUBLE
		public Assignment getNbAssignment_11() { return cNbAssignment_11; }
		
		//DOUBLE
		public RuleCall getNbDOUBLETerminalRuleCall_11_0() { return cNbDOUBLETerminalRuleCall_11_0; }
		
		//ingredients=Ingredients
		public Assignment getIngredientsAssignment_12() { return cIngredientsAssignment_12; }
		
		//Ingredients
		public RuleCall getIngredientsIngredientsParserRuleCall_12_0() { return cIngredientsIngredientsParserRuleCall_12_0; }
		
		//ustensils=Ustensils
		public Assignment getUstensilsAssignment_13() { return cUstensilsAssignment_13; }
		
		//Ustensils
		public RuleCall getUstensilsUstensilsParserRuleCall_13_0() { return cUstensilsUstensilsParserRuleCall_13_0; }
		
		//instructions=Instructions
		public Assignment getInstructionsAssignment_14() { return cInstructionsAssignment_14; }
		
		//Instructions
		public RuleCall getInstructionsInstructionsParserRuleCall_14_0() { return cInstructionsInstructionsParserRuleCall_14_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	public class UstensilsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.Ustensils");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUstensilsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUstensilsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUstrAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUstrUstensilParserRuleCall_4_0 = (RuleCall)cUstrAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Ustensils:
		//	{Ustensils} "ustensils" ":" "{" ustr+=Ustensil* "}";
		@Override public ParserRule getRule() { return rule; }
		
		//{Ustensils} "ustensils" ":" "{" ustr+=Ustensil* "}"
		public Group getGroup() { return cGroup; }
		
		//{Ustensils}
		public Action getUstensilsAction_0() { return cUstensilsAction_0; }
		
		//"ustensils"
		public Keyword getUstensilsKeyword_1() { return cUstensilsKeyword_1; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//ustr+=Ustensil*
		public Assignment getUstrAssignment_4() { return cUstrAssignment_4; }
		
		//Ustensil
		public RuleCall getUstrUstensilParserRuleCall_4_0() { return cUstrUstensilParserRuleCall_4_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class UstensilElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.Ustensil");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//Ustensil:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class IngredientsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.Ingredients");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIngredientsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIngredientsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cIngrAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cIngrIngredientParserRuleCall_4_0 = (RuleCall)cIngrAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Ingredients:
		//	{Ingredients} "ingredients" ":" "{" ingr+=Ingredient* "}";
		@Override public ParserRule getRule() { return rule; }
		
		//{Ingredients} "ingredients" ":" "{" ingr+=Ingredient* "}"
		public Group getGroup() { return cGroup; }
		
		//{Ingredients}
		public Action getIngredientsAction_0() { return cIngredientsAction_0; }
		
		//"ingredients"
		public Keyword getIngredientsKeyword_1() { return cIngredientsKeyword_1; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//ingr+=Ingredient*
		public Assignment getIngrAssignment_4() { return cIngrAssignment_4; }
		
		//Ingredient
		public RuleCall getIngrIngredientParserRuleCall_4_0() { return cIngrIngredientParserRuleCall_4_0; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class IngredientElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.Ingredient");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cSuitenameIngredientAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSuitenameIngredientIDTerminalRuleCall_1_0 = (RuleCall)cSuitenameIngredientAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cQteAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cQteDOUBLETerminalRuleCall_3_0 = (RuleCall)cQteAssignment_3.eContents().get(0);
		private final Assignment cQuantificateurAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cQuantificateurQuantificateursParserRuleCall_4_0 = (RuleCall)cQuantificateurAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cNumberSignKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cGroupAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cGroupIDTerminalRuleCall_5_1_0 = (RuleCall)cGroupAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommercialAtKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTagAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTagIDTerminalRuleCall_6_1_0 = (RuleCall)cTagAssignment_6_1.eContents().get(0);
		
		//Ingredient:
		//	name=ID suitenameIngredient+=ID* ":" qte=DOUBLE quantificateur=Quantificateurs ("#" group=ID)? ("@" tag=ID)?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID suitenameIngredient+=ID* ":" qte=DOUBLE quantificateur=Quantificateurs ("#" group=ID)? ("@" tag=ID)?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//suitenameIngredient+=ID*
		public Assignment getSuitenameIngredientAssignment_1() { return cSuitenameIngredientAssignment_1; }
		
		//ID
		public RuleCall getSuitenameIngredientIDTerminalRuleCall_1_0() { return cSuitenameIngredientIDTerminalRuleCall_1_0; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//qte=DOUBLE
		public Assignment getQteAssignment_3() { return cQteAssignment_3; }
		
		//DOUBLE
		public RuleCall getQteDOUBLETerminalRuleCall_3_0() { return cQteDOUBLETerminalRuleCall_3_0; }
		
		//quantificateur=Quantificateurs
		public Assignment getQuantificateurAssignment_4() { return cQuantificateurAssignment_4; }
		
		//Quantificateurs
		public RuleCall getQuantificateurQuantificateursParserRuleCall_4_0() { return cQuantificateurQuantificateursParserRuleCall_4_0; }
		
		//("#" group=ID)?
		public Group getGroup_5() { return cGroup_5; }
		
		//"#"
		public Keyword getNumberSignKeyword_5_0() { return cNumberSignKeyword_5_0; }
		
		//group=ID
		public Assignment getGroupAssignment_5_1() { return cGroupAssignment_5_1; }
		
		//ID
		public RuleCall getGroupIDTerminalRuleCall_5_1_0() { return cGroupIDTerminalRuleCall_5_1_0; }
		
		//("@" tag=ID)?
		public Group getGroup_6() { return cGroup_6; }
		
		//"@"
		public Keyword getCommercialAtKeyword_6_0() { return cCommercialAtKeyword_6_0; }
		
		//tag=ID
		public Assignment getTagAssignment_6_1() { return cTagAssignment_6_1; }
		
		//ID
		public RuleCall getTagIDTerminalRuleCall_6_1_0() { return cTagIDTerminalRuleCall_6_1_0; }
	}
	public class QuantificateursElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.Quantificateurs");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cQuantificateursAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cCCKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cQuantificateursAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cCSKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cQuantificateursAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Assignment cUnitAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cUnitUnitParserRuleCall_2_1_0 = (RuleCall)cUnitAssignment_2_1.eContents().get(0);
		private final Alternatives cAlternatives_2_2 = (Alternatives)cGroup_2.eContents().get(2);
		private final Keyword cGKeyword_2_2_0 = (Keyword)cAlternatives_2_2.eContents().get(0);
		private final Keyword cLKeyword_2_2_1 = (Keyword)cAlternatives_2_2.eContents().get(1);
		
		//Quantificateurs:
		//	{Quantificateurs} "càc" | {Quantificateurs} "càs" | {Quantificateurs} unit=Unit? ("g" | "l");
		@Override public ParserRule getRule() { return rule; }
		
		//{Quantificateurs} "càc" | {Quantificateurs} "càs" | {Quantificateurs} unit=Unit? ("g" | "l")
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Quantificateurs} "càc"
		public Group getGroup_0() { return cGroup_0; }
		
		//{Quantificateurs}
		public Action getQuantificateursAction_0_0() { return cQuantificateursAction_0_0; }
		
		//"càc"
		public Keyword getCCKeyword_0_1() { return cCCKeyword_0_1; }
		
		//{Quantificateurs} "càs"
		public Group getGroup_1() { return cGroup_1; }
		
		//{Quantificateurs}
		public Action getQuantificateursAction_1_0() { return cQuantificateursAction_1_0; }
		
		//"càs"
		public Keyword getCSKeyword_1_1() { return cCSKeyword_1_1; }
		
		//{Quantificateurs} unit=Unit? ("g" | "l")
		public Group getGroup_2() { return cGroup_2; }
		
		//{Quantificateurs}
		public Action getQuantificateursAction_2_0() { return cQuantificateursAction_2_0; }
		
		//unit=Unit?
		public Assignment getUnitAssignment_2_1() { return cUnitAssignment_2_1; }
		
		//Unit
		public RuleCall getUnitUnitParserRuleCall_2_1_0() { return cUnitUnitParserRuleCall_2_1_0; }
		
		//("g" | "l")
		public Alternatives getAlternatives_2_2() { return cAlternatives_2_2; }
		
		//"g"
		public Keyword getGKeyword_2_2_0() { return cGKeyword_2_2_0; }
		
		//"l"
		public Keyword getLKeyword_2_2_1() { return cLKeyword_2_2_1; }
	}
	public class UnitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.Unit");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cKKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cHKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cDaKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cDKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cCKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cMKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//Unit:
		//	"k" | "h" | "da" | "d" | "c" | "m";
		@Override public ParserRule getRule() { return rule; }
		
		//"k" | "h" | "da" | "d" | "c" | "m"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"k"
		public Keyword getKKeyword_0() { return cKKeyword_0; }
		
		//"h"
		public Keyword getHKeyword_1() { return cHKeyword_1; }
		
		//"da"
		public Keyword getDaKeyword_2() { return cDaKeyword_2; }
		
		//"d"
		public Keyword getDKeyword_3() { return cDKeyword_3; }
		
		//"c"
		public Keyword getCKeyword_4() { return cCKeyword_4; }
		
		//"m"
		public Keyword getMKeyword_5() { return cMKeyword_5; }
	}
	public class InstructionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.Instructions");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cInstructionsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cInstructionsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Instructions:
		//	{Instructions} "instructions" ":" "{" "}" //instructions+=Instruction* "END" "}"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{Instructions} "instructions" ":" "{" "}"
		public Group getGroup() { return cGroup; }
		
		//{Instructions}
		public Action getInstructionsAction_0() { return cInstructionsAction_0; }
		
		//"instructions"
		public Keyword getInstructionsKeyword_1() { return cInstructionsKeyword_1; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.Instruction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cObjAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cObjIDTerminalRuleCall_1_0 = (RuleCall)cObjAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cPreparationAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cPreparationIngredientParserRuleCall_2_1_0 = (RuleCall)cPreparationAssignment_2_1.eContents().get(0);
		private final Keyword cLineFeedKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Instruction:
		//	name=ID obj+=ID* ('->' preparation=Ingredient)? '\n';
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID obj+=ID* ('->' preparation=Ingredient)? '\n'
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//obj+=ID*
		public Assignment getObjAssignment_1() { return cObjAssignment_1; }
		
		//ID
		public RuleCall getObjIDTerminalRuleCall_1_0() { return cObjIDTerminalRuleCall_1_0; }
		
		//('->' preparation=Ingredient)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_2_0() { return cHyphenMinusGreaterThanSignKeyword_2_0; }
		
		//preparation=Ingredient
		public Assignment getPreparationAssignment_2_1() { return cPreparationAssignment_2_1; }
		
		//Ingredient
		public RuleCall getPreparationIngredientParserRuleCall_2_1_0() { return cPreparationIngredientParserRuleCall_2_1_0; }
		
		//'\n'
		public Keyword getLineFeedKeyword_3() { return cLineFeedKeyword_3; }
	}
	
	
	private final ModelElements pModel;
	private final TechniqueElements pTechnique;
	private final ChoicesElements pChoices;
	private final IngrUslTechElements pIngrUslTech;
	private final RecipeElements pRecipe;
	private final UstensilsElements pUstensils;
	private final UstensilElements pUstensil;
	private final IngredientsElements pIngredients;
	private final IngredientElements pIngredient;
	private final QuantificateursElements pQuantificateurs;
	private final UnitElements pUnit;
	private final InstructionsElements pInstructions;
	private final InstructionElements pInstruction;
	private final TerminalRule tDOUBLE;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RecipeGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pTechnique = new TechniqueElements();
		this.pChoices = new ChoicesElements();
		this.pIngrUslTech = new IngrUslTechElements();
		this.pRecipe = new RecipeElements();
		this.pUstensils = new UstensilsElements();
		this.pUstensil = new UstensilElements();
		this.pIngredients = new IngredientsElements();
		this.pIngredient = new IngredientElements();
		this.pQuantificateurs = new QuantificateursElements();
		this.pUnit = new UnitElements();
		this.pInstructions = new InstructionsElements();
		this.pInstruction = new InstructionElements();
		this.tDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "cuisine.recipe.Recipe.DOUBLE");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("cuisine.recipe.Recipe".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	defTechniques+=Technique* recipes+=Recipe*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Technique:
	//	"define" name=ID ("[" objectsFac+=IngrUslTech "]" | objects+=IngrUslTech | "{" choices "}")+;
	public TechniqueElements getTechniqueAccess() {
		return pTechnique;
	}
	
	public ParserRule getTechniqueRule() {
		return getTechniqueAccess().getRule();
	}
	
	//fragment choices:
	//	choix+=ID ("," choix+=ID)* | "{" choices "}" ("," "{" choices "}")*;
	public ChoicesElements getChoicesAccess() {
		return pChoices;
	}
	
	public ParserRule getChoicesRule() {
		return getChoicesAccess().getRule();
	}
	
	//IngrUslTech:
	//	"ingredient" | "ustensil" | "preparation" | "temperature" | "tool";
	public IngrUslTechElements getIngrUslTechAccess() {
		return pIngrUslTech;
	}
	
	public ParserRule getIngrUslTechRule() {
		return getIngrUslTechAccess().getRule();
	}
	
	//Recipe:
	//	"recipe" "{" "name" ":" name=ID suitename+=ID* "time" ":" time=DOUBLE "nb_pers" ":" nb=DOUBLE ingredients=Ingredients
	//	ustensils=Ustensils instructions=Instructions "}";
	public RecipeElements getRecipeAccess() {
		return pRecipe;
	}
	
	public ParserRule getRecipeRule() {
		return getRecipeAccess().getRule();
	}
	
	//Ustensils:
	//	{Ustensils} "ustensils" ":" "{" ustr+=Ustensil* "}";
	public UstensilsElements getUstensilsAccess() {
		return pUstensils;
	}
	
	public ParserRule getUstensilsRule() {
		return getUstensilsAccess().getRule();
	}
	
	//Ustensil:
	//	name=ID;
	public UstensilElements getUstensilAccess() {
		return pUstensil;
	}
	
	public ParserRule getUstensilRule() {
		return getUstensilAccess().getRule();
	}
	
	//Ingredients:
	//	{Ingredients} "ingredients" ":" "{" ingr+=Ingredient* "}";
	public IngredientsElements getIngredientsAccess() {
		return pIngredients;
	}
	
	public ParserRule getIngredientsRule() {
		return getIngredientsAccess().getRule();
	}
	
	//Ingredient:
	//	name=ID suitenameIngredient+=ID* ":" qte=DOUBLE quantificateur=Quantificateurs ("#" group=ID)? ("@" tag=ID)?;
	public IngredientElements getIngredientAccess() {
		return pIngredient;
	}
	
	public ParserRule getIngredientRule() {
		return getIngredientAccess().getRule();
	}
	
	//Quantificateurs:
	//	{Quantificateurs} "càc" | {Quantificateurs} "càs" | {Quantificateurs} unit=Unit? ("g" | "l");
	public QuantificateursElements getQuantificateursAccess() {
		return pQuantificateurs;
	}
	
	public ParserRule getQuantificateursRule() {
		return getQuantificateursAccess().getRule();
	}
	
	//Unit:
	//	"k" | "h" | "da" | "d" | "c" | "m";
	public UnitElements getUnitAccess() {
		return pUnit;
	}
	
	public ParserRule getUnitRule() {
		return getUnitAccess().getRule();
	}
	
	//Instructions:
	//	{Instructions} "instructions" ":" "{" "}" //instructions+=Instruction* "END" "}"
	//;
	public InstructionsElements getInstructionsAccess() {
		return pInstructions;
	}
	
	public ParserRule getInstructionsRule() {
		return getInstructionsAccess().getRule();
	}
	
	//Instruction:
	//	name=ID obj+=ID* ('->' preparation=Ingredient)? '\n';
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}
	
	//terminal DOUBLE returns ecore::EDouble:
	//	INT ('.' INT)?;
	public TerminalRule getDOUBLERule() {
		return tDOUBLE;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
